
import { Inter } from "next/font/google";
import "./globals.css";
import '@fontsource/roboto/300.css';
import theme from "../components/CustomTheme"
import { ThemeProvider } from '@mui/material/styles';
const inter = Inter({ subsets: ["latin"] });


export const metadata = {
  title: "Inventory Management",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ThemeProvider theme = {theme}>
      {children}
      </ThemeProvider>
      </body>
    </html>
  );
}
